### ISSUE TITLE
File opening crashes software

### ISSUE THREAD

**Issue by nirmaliyer** [tstana/xlcal-shutter-motor-control#1]
The software crashes (with an unhandled exception error) when we click on "New" log without filling something into the text box. This stops any running ON/OFF sequence and holds the motor in the last held position

**Comment by tstana** [comment]
This probably happens because you had started the motor control, ticked the **Use** checkbox under **Log File** and the software tried to write to an empty file name.

I see two solutions to this:

1. A pop-up message informing the user that the file name has not been selected correctly.
2. Add a default file name, e.g., in the Windows `%AppData%` folder. Note this might make the folder harder to find (`%AppData%` is normally a hidden folder and it's usually full of stuff).

Which one seems more appropriate for you?

**Comment by nirmaliyer** [comment]
I guess a pop-up is better.

As for the sequence, yes, I tried to tick the **Use** checkbox and then clicked on the **New** file button. I suppose inverting the sequence i.e., clicking on the **New** button, creating a file and then checking the **Use** box would be the "correct" way ?

**Comment by tstana** [comment]
No, the sequence should normally be Use > New (or Load).

Was the motor control running when you clicked Use?

**Comment by nirmaliyer** [comment]
Yup, the motor control was running when I clicked **Use**

**Comment by tstana** [comment]
Closed via commit 71098d5.
